#!/usr/bin/env node
/**
 * kanka-mcp Windows build - standalone kanka-mcp.exe (Node Single Executable
 * Application). The exe embeds the Node runtime and starts the MCP server in
 * HTTP mode on http://127.0.0.1:3333 by default. Configured via
 * kanka-mcp.json next to the exe, CLI flags or environment variables.
 *
 * Usage: node windows/build.mjs
 * Build machine: Node >= 20 + npm (npx fetches postject once).
 * Target machine: nothing - the Node runtime is embedded in the exe.
 *
 * server.js is the single source of truth: it is converted to a CJS SEA entry
 * at build time (its only ESM constructs are the two `import` lines, checked
 * below). Re-run this script after every server.js change - the exe is a
 * snapshot, it does not read server.js at runtime.
 */
'use strict';

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { spawn, spawnSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const BUILD = path.join(DIST, 'build');
const EXE = path.join(DIST, 'kanka-mcp.exe');
const ENTRY = path.join(BUILD, 'sea-entry.cjs');
const SEA_CONFIG = path.join(BUILD, 'sea-config.json');
const BLOB = path.join(BUILD, 'kanka-mcp.blob');
const FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';

const die = (msg) => { console.error('build: ' + msg); process.exit(1); };

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { stdio: 'inherit', ...opts });
  if (res.error) die('cannot run ' + cmd + ': ' + res.error.message);
  if (res.status !== 0) die('command failed (' + res.status + '): ' + cmd + ' ' + args.join(' '));
  return res;
}

const [major] = process.versions.node.split('.').map(Number);
if (major < 20) die('Node >= 20 required, found ' + process.versions.node);
if (process.platform !== 'win32') {
  console.error('build: warning - SEA embeds the CURRENT platform runtime; building on ' +
    process.platform + ' produces a ' + process.platform + ' binary, not a Windows exe.');
  console.error('build: run this on Windows for kanka-mcp.exe.');
}

// --- 1. server.js -> CJS SEA entry -----------------------------------------
// The exe must work without server.js on disk, and SEA needs a CJS entry.
// server.js only uses ESM for its two `import` lines (verified below).
let server = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
server = server.replace(/^#!.*\r?\n/, '');
server = server.replace(
  /^import\s+(\w+)\s+from\s+['"]([^'"]+)['"];?\s*$/gm,
  (m, name, spec) => "const " + name + " = require('" + spec + "');",
);
if (/(^|\n)\s*(import|export)\b/.test(server)) {
  die('server.js now contains ESM constructs this builder cannot convert - update windows/build.mjs');
}

const BOOTSTRAP = `// --- Windows bootstrap (generated by windows/build.mjs) --------------------
// The exe is meant to be double-clicked or run as a background process:
// always serve HTTP (never stdio). Config file loading (kanka-mcp.json next
// to the exe, cwd, %APPDATA%), the friendly error on a missing token and
// the local app banner all live in server.js itself.
if (!process.argv.includes('--http')) process.argv.push('--http');
kankaServerMain();
// ---------------------------------------------------------------------------`;

fs.mkdirSync(BUILD, { recursive: true });
fs.writeFileSync(
  ENTRY,
  BOOTSTRAP + '\nfunction kankaServerMain() {\n' + server + '\n}\n',
);

fs.writeFileSync(SEA_CONFIG, JSON.stringify({
  main: 'sea-entry.cjs',
  output: 'kanka-mcp.blob',
  disableExperimentalSEAWarning: true,
  useSnapshot: false,
  useCodeCache: false,
}, null, 2));

// --- 2. Build the SEA blob and the exe ------------------------------------
console.log('build: generating SEA blob (node ' + process.versions.node + ')...');
run(process.execPath, ['--experimental-sea-config', 'sea-config.json'], { cwd: BUILD });

console.log('build: copying runtime shell -> ' + path.relative(ROOT, EXE));
fs.copyFileSync(process.execPath, EXE);

console.log('build: injecting blob (postject)...');
const npxCli = [
  path.join(path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npx-cli.js'),
  path.join(path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js'),
].find((c) => fs.existsSync(c));
const postjectArgs = ['--yes', 'postject', EXE, 'NODE_SEA_BLOB', BLOB, '--sentinel-fuse', FUSE];
if (npxCli) {
  run(process.execPath, [npxCli, ...postjectArgs]);
} else {
  run('npx', postjectArgs, { shell: process.platform === 'win32' });
}

// --- 3. Config template next to the exe (kept if already present) ----------
const CONFIG_PATH = path.join(DIST, 'kanka-mcp.json');
if (!fs.existsSync(CONFIG_PATH)) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify({
    apiToken: '',
    defaultCampaign: null,
    apiBase: 'https://api.kanka.io/1.0',
    bind: '127.0.0.1',
    port: 3333,
    httpToken: '',
  }, null, 2) + '\n');
}

// --- 4. Smoke test: run the exe, check GET / and POST tools/list ------------
await smokeTest();

console.log('');
console.log('=== kanka-mcp.exe built ===');
console.log('Executable : ' + EXE);
console.log('Config      : ' + CONFIG_PATH + '  (edit apiToken)');
console.log('Run         : ' + EXE + '   -> http://127.0.0.1:' + 3333);
console.log('Autostart   : powershell -File windows\\install-autostart.ps1');
console.log('Docs        : DEPLOY-WINDOWS.md');

// ---------------------------------------------------------------------------
async function smokeTest() {
  const port = 33330 + Math.floor(Math.random() * 1000);
  const env = {
    ...process.env,
    KANKA_API_TOKEN: 'build-smoke-test-token',
    KANKA_MCP_PORT: String(port),
    KANKA_MCP_BIND: '127.0.0.1',
  };
  const child = spawn(EXE, [], { env, stdio: ['ignore', 'pipe', 'pipe'] });
  let out = '';
  child.stdout.on('data', (d) => { out += d; });
  child.stderr.on('data', (d) => { out += d; });
  const base = 'http://127.0.0.1:' + port;
  try {
    let ok = false;
    for (let i = 0; i < 40 && !ok; i++) {
      await new Promise((r) => setTimeout(r, 250));
      if (child.exitCode !== null) die('exe exited during smoke test:\n' + out);
      try {
        const res = await fetch(base + '/');
        ok = res.ok && (await res.json()).status === 'ok';
      } catch {}
    }
    if (!ok) die('smoke test failed: no HTTP response on ' + base + '\n' + out);
    const res = await fetch(base + '/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }),
    });
    const body = await res.json();
    const names = (body.result && body.result.tools ? body.result.tools : []).map((t) => t.name);
    if (!names.includes('kanka_search')) {
      die('smoke test failed: tools/list missing kanka_search\n' + JSON.stringify(body).slice(0, 400));
    }
    console.log('build: smoke test ok - GET / -> ok, tools/list -> ' + names.length +
      ' tools, port ' + port);
  } finally {
    child.kill();
    await new Promise((r) => child.once('exit', r));
  }
}
